name: adventofcode2020

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - attoparsec
  - containers
  - text

ghc-options: -Wall

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

executables:
  day1:
    source-dirs: src/apps/Day1
    main: Main.hs
    dependencies:
    - adventofcode2020
  day5:
    source-dirs: src/apps/Day5
    main: Main.hs
    dependencies:
    - adventofcode2020
  day8:
    source-dirs: src/apps/Day8
    main: Main.hs
    dependencies:
    - adventofcode2020
  day9:
    source-dirs: src/apps/Day9
    main: Main.hs
    dependencies:
    - adventofcode2020
library:
  source-dirs: src/library
  exposed-modules: Common
